#Requires -Version 3.0

<#
	.SYNOPSIS
	Generates a list of values based on the CSEntry attribute values that will be used to search the metaverse.

	.PARAMETER FlowRuleName
	Contains the name of the flow rule. You must use only alphanumeric characters for the FlowRuleName parameter; otherwise you can encounter problems in a rules extension.

	.PARAMETER csentry
	Contains a CSEntry object that represents the connector space entry.

	.PARAMETER values
	Contains a ValueCollection object that receives the list of attribute values that are generated by this method to be used to search the metaverse.

	.NOTES
	Flow rules are not executed in the order shown in Synchronization Service Manager. Forefront Identity Manager Synchronization Service (FIM Synchronization Service) uses these rules according to the state of the connector space object. Configure your rules based on the state of the object rather than the rules being called in a predetermined order.

	Use this method to convert attribute values to a format used in the metaverse. For example, the metaverse stores the full name attribute as a single string made up of the first name and last name, while the connected data source stores a first name and a last name as separate attributes. You can use this method to combine a first name and last name into a single string that can be used to search the full name attribute in the metaverse.

	.LINK
	http://msdn.microsoft.com/en-us/library/microsoft.metadirectoryservices.imasynchronization.mapattributesforjoin(v=vs.100).aspx
#>
[CmdletBinding()]
param(
	[Parameter(Mandatory)]
	[ValidateNotNullOrEmpty()]
	[string] $FlowRuleName, 
	
	[Parameter(Mandatory)]
	[ValidateNotNull()]
	[csentry] $csentry, 

	[Parameter(Mandatory)]
	[ValidateNotNull()]
	[ValueCollection] $values
)
