#Requires -Version 3.0

<#
	.SYNOPSIS
	Called when a join rule is configured to use a rules extension to resolve conflicts, and when one or more results from a metaverse search match the values that are generated by the MapAttributesForJoin method.

	.PARAMETER JoinCriteriaName
	Contains a string that contains the name of the join criteria. You must use only alphanumeric characters for the joinCriteriaName parameter, otherwise you can encounter problems in a rules extension.

	.PARAMETER csentry
	Contains the CSEntry object that represents the connector space entry that will be joined to the metaverse entry.

	.PARAMETER rgmventry
	Contains an array of CSEntry objects that represent the metaverse entries that match the join operation criteria. On return, the imventry parameter receives the index of the object in this array to which the connector space entry will be joined.

	.PARAMETER MVObjectType
	Contains a string that contains the name of the metaverse class.

	.OUTPUTS
	The index of the object in the rgmventry parameter to which the connector space entry will be joined.

	.LINK
	http://msdn.microsoft.com/en-us/library/microsoft.metadirectoryservices.imasynchronization.resolvejoinsearch(v=vs.100).aspx
#>
[CmdletBinding()]
param(
	[Parameter(Mandatory)]
	[ValidateNotNullOrEmpty()]
	[string] $JoinCriteriaName, 
	
	[Parameter(Mandatory)]
	[ValidateNotNull()]
	[csentry] $csentry, 
	
	[Parameter(Mandatory)]
	[ValidateNotNullOrEmpty()]
	[mventry[]] $rgmventry,

	[Parameter(Mandatory)]
	[ValidateNotNullOrEmpty()]
	[string] $MVObjectType
)

begin {
	$imventry = -1
}

process {
}

end {
	$imventry
}